# taken from Nangate45.pdn.tcl
####################################
# global connections
####################################
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^VDD$} -power
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^VDDPE$}
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^VDDCE$}
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {^VSS$} -ground
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {^VSSE$}
global_connect
####################################
# voltage domains
####################################
set_voltage_domain -name {CORE} -power {VDD} -ground {VSS}
####################################
# standard cell grid
####################################
define_pdn_grid -name {grid} -voltage_domains {CORE}
add_pdn_stripe -grid {grid} -layer {metal1} -width {0.17} -pitch {2.4} -offset {0} -followpins
add_pdn_stripe -grid {grid} -layer {metal4} -width {0.48} -pitch {56.0} -offset {2}
add_pdn_stripe -grid {grid} -layer {metal7} -width {1.40} -pitch {40.0} -offset {2}
add_pdn_connect -grid {grid} -layers {metal1 metal4}
add_pdn_connect -grid {grid} -layers {metal4 metal7}


####################################
# Minimal (dummy) macro PDN grids
#
# Explanation:
# OpenROAD automatically treats any cell taller than 6 placement rows
# as a "macro". For every macro, the PDN engine *requires* that a
# macro-level PDN grid be defined, or else the global PDN generation
# will fail with PDN-0232/PDN-0233 errors.
#
# However, the macros generated by MacroMaker (e.g., Add16, Mult32, etc.)
# are NOT true hard macros like SRAMs or embedded IP. They:
#   • only contain simple metal1 VDD/VSS rails,
#   • do not have power pins on higher metals (M4/M5/M6),
#   • do not support dedicated macro power meshes,
#   • and should be powered entirely by the standard-cell PDN grid.
#
# A full macro PDN (with M5/M6 stripes) causes failures because the
# stripes often do not intersect the macro area after halo reduction.
#
# Therefore:
#   We define a *minimal dummy macro PDN grid* that satisfies OpenROAD’s
#   requirement that every macro have a PDN grid, but without creating
#   a real macro power mesh. This grid places a single tiny metal1
#   followpins stripe that always intersects the macro area. It does not
#   affect routing or real power delivery, but it prevents PDN-0232/0233.
#
# Result:
#   • Macros are considered “powered” by OpenROAD’s PDN engine.
#   • Standard-cell PDN (with metal1 followpins) delivers power normally.
#   • No macro-mesh conflicts, no fatal PDN errors, and no large area.
####################################

# For macros with no rotation (R0/MX/MY/R180)
define_pdn_grid -name {CORE_macro_grid_1} \
    -macro \
    -voltage_domains {CORE} \
    -orient {R0 R180 MX MY} \
    -halo {0.1 0.1 0.1 0.1} \
    -grid_over_boundary

add_pdn_stripe -grid {CORE_macro_grid_1} \
    -layer {metal1} \
    -width {0.05} \
    -pitch {1000} \
    -offset 0.0 \
    -followpins

# For macros rotated by 90°
define_pdn_grid -name {CORE_macro_grid_2} \
    -macro \
    -voltage_domains {CORE} \
    -orient {R90 R270 MXR90 MYR90} \
    -halo {0.1 0.1 0.1 0.1} \
    -grid_over_boundary

add_pdn_stripe -grid {CORE_macro_grid_2} \
    -layer {metal1} \
    -width {0.05} \
    -pitch {1000} \
    -offset 0.0 \
    -followpins
####################################