# This file contains code from NVSim, (c) 2012-2013,  Pennsylvania State University
#and Hewlett-Packard Company. See LICENSE_NVSim file in the top-level directory.
#No part of DESTINY Project, including this file, may be copied,
#modified, propagated, or distributed except according to the terms
#contained in the LICENSE file.

WARNING = 0

INV = 0
NOR = 1
NAND = 2

NMOS = 0
PMOS = 1

MAX_INV_CHAIN_LEN = 20
OPT_F = 4

COMPARATOR_INV_CHAIN_LEN = 4

MAX_NMOS_SIZE = 100
MIN_NMOS_SIZE = 1.5

AREA_OPT_CONSTRAIN = 1

MAX_TRANSISTOR_HEIGHT = 20

MIN_GAP_BET_P_AND_N_DIFFS = 2
MIN_GAP_BET_SAME_TYPE_DIFFS = 1.5
MIN_GAP_BET_POLY = 1.5
MIN_GAP_BET_CONTACT_POLY = 0.75
CONTACT_SIZE = 1
MIN_WIDTH_POWER_RAIL = 2

AVG_RATIO_LEAK_2INPUT_NAND = 0.48
AVG_RATIO_LEAK_3INPUT_NAND = 0.31
AVG_RATIO_LEAK_2INPUT_NOR = 0.95
AVG_RATIO_LEAK_3INPUT_NOR = 0.62

W_SENSE_P = 7.5
W_SENSE_N = 3.75
W_SENSE_ISO = 12.5
W_SENSE_EN = 5.0
W_SENSE_MUX = 9.0
VBITSENSEMIN = 0.08
IV_CONVERTER_AREA = 50000

STITCHING_OVERHEAD = 7.5

DRAM_REFRESH_PERIOD = 64e-3

SHAPER_EFFICIENCY_CONSERVATIVE = 0.2
SHAPER_EFFICIENCY_AGGRESSIVE = 1.0

COPPER_RESISTIVITY = 2.2e-8  # Unit: ohm*m at 20 celcius degree
COPPER_RESISTIVITY_TEMPERATURE_COEFFICIENT = 0.0039
PERMITTIVITY = 8.85e-12  # Unit: F/m

TUNNEL_CURRENT_FLOW = 10  # Unit: A/m^2
DELTA_V_TH = 5.0  # Unit: V, Threshold difference of floating gate

RES_ADJ = 8.6
VOL_SWING = .1

CONSTRAINT_ASPECT_RATIO_BANK = 3

BITLINE_LEAKAGE_TOLERANCE = 1
IR_DROP_TOLERANCE = 0.2

TOTAL_ADDRESS_BIT = 48

MAX_NUMBER_GATES_STAGE = 20
NUMBER_INTERCONNECT_PROJECTION_TYPES = 2  # Conservative or Aggressive
fopt = 4.0

BULK_CU_RESISTIVITY = 0.018  # ohm-micron
PERMITTIVITY_FREE_SPACE = 8.854e-18  # F/micron
